- name: Get vault credentials
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
  tasks:
    - name: Print Password
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'test/data/my_credentials:password token={{ vault_token }} url=https://10.0.1.135:8200 validate_certs=False')}}"